name: projekt_it
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  camera: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
      - asset: lib/fonts/montserrat/Montserrat-Regular.ttf
      - asset: lib/fonts/montserrat/Montserrat-Italic.ttf
        style: italic
      - asset: lib/fonts/montserrat/Montserrat-Bold.ttf
        weight: 700
    - family: Prata
      fonts:
      - asset: lib/fonts/prata/Prata-Regular.ttf
    - family: Meddon
      fonts:
      - asset: lib/fonts/meddon/Meddon-Regular.ttf

  assets:
    - lib/assets/
