name: projekt_it
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
